SELECT * FROM customer

--Total revenue generated by male and female
select gender,sum(purchase_amount) as total_revenue
from customer 
group by gender
order by total_revenue desc

--customers used discount but still spent more than the average amount

 select customer_id,purchase_amount
 from customer
 where discount_applied='Yes'and
 purchase_amount>=(select avg(purchase_amount) from customer)


--Top 5 products with the highest average review rating
 select item_purchased,
 Round(avg(review_rating::numeric),2)
 as average_product_rating from customer
 group by item_purchased
 order by avg(review_rating)desc
 limit 5;

--comparing average purchase amount between standard and express shipping
select shipping_type,Round(avg(purchase_amount),2)
from customer
where shipping_type in('Standard','Express')
group by shipping_type


--Do subscribed customers spend more?compare average spend and total revenue between subscribers and non subscribers

select subscription_status,
count(customer_id)as total_customers,
Round(avg(purchase_amount),2)as average_spend,
Round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_customers desc;

--which 5 products have the highest percentage of purchases with discounts applied
select item_purchased,
Round(100*sum(case when discount_applied='Yes' Then 1 Else 0 END)/count(*),2)as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--segment customers into new,returning and loyal based on their total
--number of previous purchases and show the count of each segment
with customer_type as(
select customer_id,previous_purchases,
CASE
    WHEN previous_purchases=1 Then 'New'
	WHEN previous_purchases Between 2 and 10 Then 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)
select customer_segment,count(*)as "number of customers"
from customer_type
group by customer_segment

--top 3 most purchased products within each category
with item_counts as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)Desc)as item_rank
from customer
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;

--Are customers who are repeat buyers (more than 5 previous purchases)also likely to subscribe?
select subscription_status,
count(customer_id)as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

--revenue contribution of each age group
select age_group,
sum(purchase_amount) as contribution
from customer
group by age_group
order by contribution desc;
